zkp-mgr for bri-2
ethereum-oasis/baseline pull request #311
Opened 2021-03-03 21:08 UTC by bitwiseguy

# Description

Adds a zero-knowledge proof microservice (written in Golang) to bri-2. This service acts as a REST server which wraps the [gnark](https://github.com/ConsenSys/gnark) library functions.

Functionality of this service includes:

1. compiling circuits
2. generating proofs
3. verifying proofs

## How Has This Been Tested

Included in this PR is a collection of Postman REST requests that can be used to try out the service. Future work will include end-to-end integration tests for all components within bri-2.

2021-03-17 19:55 UTC, breakpointer approved these changes

2021-03-18 23:35 UTC, Meuko commented on examples/bri-2/zkp-mgr/README.md
> +The `zkp-mgr` service is a REST server written in Golang which wraps the [gnark](https://github.com/ConsenSys/gnark) zero-knowledge proof functions. A user can upload circuit source code (written in
> A _**future**_ improvement

2021-03-18 23:38 UTC, Meuko requested changes
Small typo in the readme, rest looks great!

2021-03-18 23:39 UTC, Meuko approved these changes
Please ignore my previous comment, I need sleep.

2021-03-19 17:01 UTC, merged